# -*- coding: utf-8 -*-
"""DA_Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VZobC3ALjjiX7WbAwwMs4LWlUMJoo6hk
"""

import pandas as pd

dir(pd)

#creating a list 'data'
data=[  #nested list[]
    [1,"neha","Mgr"],
    [2,"Nisha","programmer"],
    [3,"Sonali","Hr"]]
data

#Pandas has two components series and dataframe
#create dataframe from list
df1=pd.DataFrame(data)
df1

#Add column name
df2=pd.DataFrame(data,columns=('Eid','Ename','Job'))
df2

se=pd.Series(data)
se

#Add column name #change indexing
df3=pd.DataFrame(data,columns=('Eid','Ename','Job'),index=('E1','E2','E3'))
df3

dfuni=pd.read_csv('/content/Universities.csv')
dfuni

dfuni.head() #top 5 will represent

dfuni.tail() #bottom 5 will represent

dfuni.tail(7)

dfuni.head(10)

