# -*- coding: utf-8 -*-
"""Python-day1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/169jq6ax01kPXgs1Kkg5jUBzP8kMjSeSk
"""

#variable
a=12

a

#variable
age=22
marks=45
avg=8.6
sal=80000

print(age,marks, avg, sal)

#to see the datatype of the variable type()
type(age)

type(avg)

name = 'Abhilash'

type(name)

a = True

type(a)

s=3+4j
s
type(s)

#Basic Arthetic Operator +,-,*,/,//,%,**.

a=4
b=6
c=a+b
print(c)

a=4
b=6
c=a-b
print(c)

a=4
b=6
c=a*b
print(c)

a=46
b=6
c=a/b
print(c)

a=46
b=6
c=a//b
print(c)

a=4
b=6
c=a%b
print(c)

a=4
b=6
c=a**b
print(c)

#floor division result in int format
hello=46
hi=6
c=hello//hi
print(c)

#for power
a=4
b=3
c=a**b
print(c)

#comparess operatoe
a=6
b=7
print(a>b)
print(a<b)
print(a>=b)
print(a<=b)
print(a==b)
print(a!=b)

a=6
b=7
a<b

a=7
b=7
a>b

a=7
b=7
a>=b

a,b=5,4

a>=b and b>=a

a,b=5,4
c,d=7,7

a>=b and c==d

x=True
y=False

x and y

x or y

not y

not x

name="Abhilash"
name

type(name)

dir(str)#all method that can be applied on string
#__magic method/dunder (double underscore method which python uses internally)

str1="welcome to Data science"
str1.capitalize()

str1

str1.upper()

str1.lower()

food="bIrYAni"
name="AbhiLAsH"
print(food.swapcase(),name.swapcase())

s1="My name is Abhilash"
s1.split()#list of string is created

s2="Mumbai-Pune-Hyderabad"
s2.split()

s2="Mumbai-Pune-Hyderabad"
s2.split("-")

s3="abc@excelr.com"
s3.split("@")

s1="My name is Nisha"
s1.replace("Nisha","Anusha")

city="hyderabad"
city.count("a")

"hyderabad".count("d")

n1=5
n1*5

name="Abhi"
name*3

name="Abhilash"#concate function
surname="Gangojipeta"
name + surname

name="Abhilash"#concate function
surname="Gangojipeta"
name +" "+ surname

#condistional statement
#if ,if else, elif

age=12
if age>=18:
  print("eligible for vote")
else:
  print("not eligible")

a=16300
b=22053
if a>b:
  print("a is greater")
  print("In True Block")
  c=a+b
  print(c)
else:
  print("b is greater")
  print("In False Block")
  c=a*b
  print(c)

a=9
b=5
if a>b:
  print("a is greater")
else:
  print("b is greater")

sal=25000
if sal>20000:
  tax=0.25
  print("I am from True if")
else:
  tax=0.20

print("now i am outside the else block where i have to calucate net sal")
net_sal=sal-tax*sal
print("net_sal",net_sal)

