# -*- coding: utf-8 -*-
"""Python-day2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HquOrhC7a6VLZOvkA6IDHUdgf1oWSUgM
"""

#Looping- range functions (start, stop, steps) (0(lower bound),10(upper bound),u-1)
range(0,10,1)

for i in range(0,10,4):
  print(i)

print("hello")
print("hello")
print("hello")
print("hello")

for i in range(1,6):
  print("hello",i)

for i in range(5,10):
  print(i)
print("Bye")

for i in range(1,11):
  print(i)

#print add number from 1 to 10
for i in range(1,10,2):
  print(i)

#even number
for i in range(2,11,2):
  print(i)

#print all even no from 1 to 20
for i in range(2,21,2):
  print(i)

#print all odd no from 1 to 20
for i in range(1,20,2):
  print(i)

#'break' statement terminate the loop when the condition is satisfied
for i in range(1,11):
  if i==5:
    print("same")
    break
  else:
    print(i)

for num in range(11): #we are not giving any start and step but its takes from 0 by defult
  print(num,num**2) #power num**2 calucate

#range (start, stop, step)
for i in range(1,31,5):
  #print(i)
  print(i,"@")

subject="Data Science"
a=len(subject)
print("a=",a)
for i in range(12):
  print(i,subject[i])

subject = "Machine Learning"
a=len(subject)
print(a)
for i in range(16):
  print(i,subject[i])

#print name 3 times on first line 4 time in 2nd line, 5 in 3rd 6 in 4th, range 3 to7
name = "Abhilash"
for i in range(3,7):
  print(name*i)

#print each letter of movie on seperate line
#change case of each letter (upper to small and small to upper)of movie on a single linewith seperator
movie="Drishyam"
for letter in movie:
  print(letter.swapcase(),end=" * ")

#print all even numbers and odd numbers between given range using for loop
for i in range(1,11):
  if(i%2==0):
    print("even number",i)
  else:
    print("odd number",i)

for i in range(1,11):
  if(i%2==0):
    print("even number",i,end="")
print(" ")
for i in range(1,11):
  if(i%2==1):
    print("odd number",i,end="")

#print each letter 4 time with sepeator as space
for letter in "Data Science":
  print(letter*4,end=" ")

len("data science")

len("Abhilash")

"""#Data Structure:- 1 List ordered Data type
#Lists are mutable
#create using square brackets[ ]
#Duplicates allowed
"""

marks=[40,55,35,70,80,60,40]
print(marks)
print(type(marks))

l1=[1,2,3,1]
l1

type(l1)

dir(list)

#append function will add elements from the last only.
marks=[40,55,35,70,80,60,40]
marks.append(100)  #append is add the elements
marks

students=["Abhi","Arun","Sailu","shakeel","shiva"]
students.append("yogesh")
students

marks=[40,55,35,70,80,60,40]
marks.insert(2,65)
marks

#Sorting in ascending order
marks=[40,55,35,70,80,60,40]
marks.sort()
marks

#sorting in descending order
marks=[40,55,35,70,80,60,40]
marks.sort(reverse=True)
marks

marks=[40,55,35,70,80,60,40]
marks.reverse()
marks

#if u want to check wheather 80 is present in the list or not.
80 in marks

40 in marks

45 in marks

list1=[10,20,30,40] #concatenation and merge of list
list2=[40,41,42,43]
list1+list2

print((list1+list2)*3,end=" ") #Repeate 3 times

stationary=['pen','pencial','sharpner']
stationary

len(stationary)

stationary.append(["book","notebook"])
stationary

len(stationary)

stationary.pop() #pop is removing the elements from last functions

stationary

stationary.pop(0)

stationary

stationary=['pen','pencil','sharpner']
stationary

stationary=['pen','pencil','sharpner']
stationary.remove('pen')

stationary

stationary.index('pencil')

stationary.index('sharpner')

stationary

stationary.extend(['book','notebook','pen'])

stationary

stationary.clear()

stationary

stationary=['pen','pencil','sharpner']
stationary.append(["Book", "Notebook"])

stationary.pop()

stationary.extend(['pen','pencil','sharpner'])

stationary

#How to get value from user
age=int(input("enter the value"))
if age>=18:
  print("can vote")
else:
  print("can not")

age=int(input("enter the value"))
if age>=18:
  print("can vote")
else:
  print("can not")

#SIMPLE INTREST P, A,T / 100
p=float(input("enter value p"))
t=int(input("enter value t"))
r=int(input("enter value r"))
si=p*t*r/100
print("si",si)

#Accept marks from user, if marks >=80 "Dist" if between 60-80print "first class"
#if between 40-60 print "pass if less than 40 print fail"
marks=int(input("enter marks"))
if marks>=80:
  print("Dist")
elif marks>=60:
  print("first class")
elif marks>=40:
  print("pass")
else:
  print("fail")

markslist=[35,55,77,95,20]
for marks in markslist:
  if marks>=80:
    print(marks,"--->Dist")
  elif marks>=60:
    print(marks,"--->first class")
  elif marks>=40:
    print(marks,"--->pass")
  else:
    print(marks,"--->fail")

