# -*- coding: utf-8 -*-
"""Python day-4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ERmAjnJVl5EIC9quBJHyRkiScUcoaiPg
"""

Student={1:"Naman",2:"Ravi",3:"Rajat"}
Student

mylist=["Mango","Orange","Banana","Apple","Papaya"]

mytuple=(20.5,30,40,60,70)

mydict={"A":mylist,"B":mytuple,"C":Student}

mydict

mydict.keys()

mydict.values()

mydict.items()

mydict['A']

mydict['B']

mydict['C']

mydict['A'][4]

mydict['A'][3]

mydict['C'][2]

from math import sqrt #math functions
sqrt(25)

from math import factorial
factorial(5)

abs(-4)

from math import sin,cos,tan
cos(0)

tan(1)

sin(1)

from math import *
listn=[5,4,2]
prod(listn)

import math
dir(math)

import math as mt
mt.sqrt(25)

mt.pow(5,2)

mt.pow(5,6)

import datetime as dt
dt.datetime(22,3,12)

dt.date(2025,7,27)

import string
dir(string)

from datetime import date
d=date(2025,7,25)
print(d)

from datetime import date
d=date.today() #combo function
print(d)

from datetime import date
d=date.today()
print(d)
print(d.year)
print(d.month)
print(d.day)

